version: "3.6"

services:

  proxy:
    image: dockerflow/docker-flow-proxy
    networks:
      - proxy
    ports:
      - '8003:8003'
      - '8080:8080'
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - DEFAULT_PORTS=8003
      #- CONNECTION_MODE=${CONNECTION_MODE:-http-server-close}
      #- TIMEOUT_HTTP_REQUEST=15
      #- TIMEOUT_CONNECT=15
      - BIND_PORTS=8003
      #- MODE=default
      #- BIND_PORTS=8003
      #- DEBUG=false
  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]
  backend:
    build: ./backend
    image: registry:5000/backend-demo
    hostname: "{{.Node.Hostname}}-backend"
    networks:
      - proxy
    #ports:
    #  - '8003:80'
    deploy:
      labels:
        - com.df.notify=true
        #- com.df.distribute=true
        #- com.df.connectionMode=http-keep-alive
        - com.df.servicePath=/
        #- com.df.reqPathSearch=/
        - com.df.port=8003
        #- com.df.srcPort=80
networks:
  proxy:
    external: true
