version: "3.6"

services:

  proxy:
    image: dockerflow/docker-flow-proxy
    networks:
      - proxy
    ports:
      - '8003:80'
      - '8080:8080'
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - DEFAULT_PORTS=80
      - BIND_PORTS=80
  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]
  backend:
    build: ./backend
    image: registry:5000/backend-demo
    hostname: "{{.Node.Hostname}}-backend"
    networks:
      - proxy
    deploy:
      labels:
        - com.df.notify=true
        - com.df.servicePath=/
        - com.df.port=80
        - com.df.srcPort=8003
networks:
  proxy:
    external: true
