version: "3.6"
services:
    backend:
      build: ./backend
      image: registry:5000/backend-demo
      hostname: "{{.Node.Hostname}}-backend"
      networks:
        - proxy
      deploy:
        labels:
          - com.df.notify=true
          - com.df.distribute=true
          - com.df.servicePath=/
          - com.df.port=8003
          - com.df.srcPort=80
    #node:
    #  image: docker:stable-dind
    #  privileged: true
    #registry:
      #restart: always
    #  image: registry:2
    #  hostname: "{{.Node.Hostname}}-registry"
    #  volumes:
    #    - registry:/var/lib/registry
    #  networks:
    #    - proxy
    #  deploy:
    #    labels:
    #      - com.df.notify=true
    #      - com.df.servicePath=/
    #      - com.df.port=5000
    #      - com.df.srcPort=5000
volumes:
  registry:
networks:
  proxy:
    external: true
